[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv

; We are now hardcoding credentials in src/wifi.cpp and src/http.cpp 
; to avoid shell escaping issues with spaces in SSIDs.
board_build.cmake_extra_args = 
    -DIGNORE_CMAKE_ARGS=1
